# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40769130364815915ce4f0941af835d48841e9e65d338916e37efe177e77f4828a75b801e4ce4e5d68fa92c81e9b2870821a82b15cba7027bc91b82bc46565fe

test:
  secret_key_base: 958cccfc6d033c3f87f358ad41dcbf22a9bdaab8e5b08582eb9ac6d50c59402a8dce1083d4564fddf59a5c0cb50600c4c76b5440e7e30cccc0cd7ca1a92a4d9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
